### ISSUE TITLE
File browser — add a 'select all'-like feature

### ISSUE THREAD

**Issue by peter-hitchcock** [OSC/ondemand#2428] opened 2022-12-13 14:23 UTC
It would be helpful to be able to select all files in a directory in the OOD file explorer instead of having to click each individually when, e.g., downloading a large set of files.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203546587384885) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment] 2022-12-13 14:53
Hi! Thank you for the ticket. Unfortunately it's a duplicate of #1177, so I have to close this. But please upvote that one (by adding a thumbs up) if you like.

That said - it's currently slated for 2.1 (the next release). So, we'll see if we can do it.

Again, thanks for the ticket! I don't want to you think me closing this is is saying no, or that we won't do it. It's really that we just already have a ticket for the same. Please open any other tickets as you like.

**Closed by johrstrom** 2022-12-13 14:53 UTC

**Comment by peter-hitchcock** [comment] 2022-12-13 14:56
Ahh sorry, for missing the previous issue! Thanks — that's great it's slotted for the next release.

**Comment by johrstrom** [comment] 2022-12-13 15:37
No problem at all. Indeed, we don't get many user generated tickets, so please if you see anything more feel free to open more tickets!
