### ISSUE TITLE
BUNDLE_USER_CONFIG seems to be ignored in some cases causing PUN to fail to start

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#1444] opened 2021-10-11 13:48 UTC
With the following in `~/.bundle/config` I am unable to launch my PUN. Removing this file resolves all issues.

## ```
BUNDLE_PATH: vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: true

```

This is the backtrace when get Passenger error when launching PUN:

```

[ N 2021-10-11 09:30:01.5162 61457/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2021-10-11 09:30:01.5165 61457/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2021-10-11 09:30:01.5451 61457/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 61457
App 61523 output: Error: The application encountered the following error: Could not find rails-5.2.6 in any of the sources (Bundler::GemNotFound)
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/spec_set.rb:90:in `block in materialize'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/spec_set.rb:85:in `map!'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/spec_set.rb:85:in `materialize'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/definition.rb:244:in `specs_for'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/runtime.rb:18:in `setup'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler.rb:149:in `setup'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/setup.rb:20:in `block in <top (required)>'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/ui/shell.rb:136:in `with_level'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/ui/shell.rb:88:in `silence'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/gems/gems/bundler-2.2.24/lib/bundler/setup.rb:20:in `<top (required)>'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
App 61523 output:     /opt/rh/rh-ruby27/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
App 61523 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:365:in `activate_gem'
App 61523 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
App 61523 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:529:in `running_bundler'
App 61523 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
App 61523 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:86:in `load_app'
App 61523 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:116:in `block in <module:App>'
App 61523 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:382:in `run_block_and_record_step_progress'
App 61523 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:115:in `<module:App>'
App 61523 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:28:in `<module:PhusionPassenger>'
App 61523 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:27:in `<main>'
[ E 2021-10-11 09:30:01.9824 61457/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/ood/apps/sys/dashboard: The application encountered the following error: Could not find rails-5.2.6 in any of the sources (Bundler::GemNotFound)
 Error ID: f6923525
 Error details saved to: /tmp/passenger-error-rDdsxm.html
```



┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737444051415) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment] 2022-04-25 15:53
duplicate of #1749.

**Closed by johrstrom** 2022-04-25 15:53 UTC
