### ISSUE TITLE
interrupting a running script makes the terminal not showing any keyboard input

### ISSUE THREAD

**Issue by lifengjin** [OSC/ondemand#448] opened 2019-04-24 14:48 UTC
This has been going on for a while with the OSC OnDemand portal. If I open a terminal on say Pitzer, and run a script, and then Ctrl-C it, there is a high chance for the terminal window to stop displaying any keyboard input at all, showing up as no new letters appearing at the cursor with keyboard pushes. The only way to restore it is to close the browser tab and reopen it. Refreshing the tab does not work.

**Comment by johrstrom** [comment] 2020-07-17 14:18
Duplicate of #147

**Closed by johrstrom** 2020-07-17 14:18 UTC
Labels: component/shell, needs investigation
