### ISSUE TITLE
Create functionality to hide/show options based on checkbox selection (similar to Dynamic JS with Drop-Downs)

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ondemand#2006] opened 2022-05-10 13:55 UTC
[https://discourse.openondemand.org/t/dynamic-behaviour-with-check-box/2060](https://discourse.openondemand.org/t/dynamic-behaviour-with-check-box/2060)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202253915196246) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment] 2022-05-10 15:39
duplicate of #1633?

**Comment by gerald-byrket** [comment] 2022-05-10 15:56
I’m going to change the main issue 1633 to an epic then.

Thanks,
Gerald Byrket
***@***.******@***.***>
817-507-6993

**Comment by gerald-byrket** [comment] 2022-05-10 16:22
Closing in lieu of #1633

**Closed** 2022-07-18 17:52 UTC
Labels: epic
