### ISSUE TITLE
ACL Editor

### ISSUE THREAD

**Issue by multimeric** [OSC/ondemand#3320] opened 2024-01-25 07:00 UTC
I'd be interested in the file manager app supporting an editor for file permissions, including Linux ACLs. Happy to discuss the design and hopefully I could find time to implement it myself.

**Comment by johrstrom** [comment] 2024-01-25 14:24
Do you mind if I close this? It's a duplicate of #2609

**Comment by multimeric** [comment] 2024-01-25 23:54
No, that's even better that it was on your roadmap!

**Closed** 2024-01-25 23:53 UTC
