### ISSUE TITLE
Require `DEFAULT_SSHHOST` to be set in order for the ssh default URL to work

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#506] opened 2020-05-20 01:02 UTC
Defaulting the default ssh host to localhost is a insecure default.

1. Instead of defaulting to localhost, if `DEFAULT_SSHHOST` is not set, we should display an error explaining that `DEFAULT_SSHHOST`. (simplest straightforward solution)

**Comment by treydock** [comment] 2020-05-20 16:37
Why not use cluster configs? I feel like it's probably confusing for sites to have some things defined in cluster configs and other things defined in environment variables. I tend to lean towards centralized configs rather than configs in multiple places.

**Comment by matthu017** [comment] 2020-05-27 14:27
Duplicate of: https://github.com/OSC/ondemand/issues/508

**Closed by matthu017** 2020-05-27 14:27 UTC
Labels: component/shell, interns
