### ISSUE TITLE
Chrome copy-paste hack can freeze noVNC session

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#356] opened 2019-12-18 21:47 UTC
While troubleshooting a question for an OSC user I attempted to paste 0.5MB of plain text using the Chrome copy/paste hack for noVNC. I got a noVNC error message saying `Uncaught RangeError: Invalid typed array length: $SOME_INTEGER`. `$SOME_INTEGER` appeared to be the same size as the character count of the text that I was pasting. After I saw the error message the noVNC session locked up, so I went back to the sessions view and launched a new connection. The new connection was also locked up and immediately showed me a similar error.

~~Attempting to paste the same content through the 'drawer' only breaks the current noVNC connection. Subsequent connections are not impacted.~~

Related: #198.
Caused by: #335.

**Comment by ericfranz** [comment] 2019-12-19 01:27
Did it freeze only after doing ctrl-shift-v or selecting "paste" from a dropdown?

**Comment by MorganRodgers** [comment] 2019-12-19 15:14
It freezes as soon as the client clipboard has too much data on it. As soon as the client clipboard's size is reduced (by copying something smaller) a new connection can be made to a running session which will succeed. So users may see the error:

- Chrome: on session connect an immediate error
- Chrome: mid-session an error pops up
- Any browser: when attempting to paste lots of data into the clipboard drawer

![Screen Shot 2019-12-19 at 9 54 29 AM](https://user-images.githubusercontent.com/13316545/71184369-abe2a080-2247-11ea-9d37-ac424bbc5619.png)

**Comment by ericfranz** [comment] 2019-12-19 16:08
If you paste in >10232 bytes into the clipboard input, this error occurs due to https://github.com/OSC/ondemand/blob/bee35f9992d7de410f89b365af1be001300cdb03/apps/dashboard/public/noVNC-1.0.0/app.v2.js#L8037-L8039

In that code, buff length is 10240 and 8 padding in front with 0 offset resulting in a 10232 buffer size. This is where that limit is set: https://github.com/OSC/ondemand/blob/bee35f9992d7de410f89b365af1be001300cdb03/apps/dashboard/public/noVNC-1.0.0/app.v2.js#L9362

Unfortunately the offset is variable based on the number of messages "queued" for sending: https://github.com/OSC/ondemand/blob/bee35f9992d7de410f89b365af1be001300cdb03/apps/dashboard/public/noVNC-1.0.0/app.v2.js#L9515-L9522

So it seems like there are two fixes to apply. 

1. Do not allow pasting more than 10232 characters in the input field. This is the maximum you can copy and paste using NoVNC.
2. Before calling `RFB.messages.clientCutText(this._sock, text);`, verify the buffer actually has enough space to write this text; if it does not, delay/repeatedly try until it does. Ideally we would hook it into an event once sock.flush() was called and completed, but I didn't see that.

**Comment by MorganRodgers** [comment] 2019-12-19 16:12
Thanks Eric. good sleuthing.

**Comment by ericfranz** [comment] 2019-12-19 18:28
The easy fixes are as follows:

1. Make _sQbufferSize the same size as _rQbufferSize (4MB)
2. Set that limit on the textarea with id noVNC_clipboard_text in the html file

Another thing I noticed that seems erroneous. [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) and [charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) deal with UTF-16. The send queue buffer is a [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array), not [Uint16Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array). See https://github.com/OSC/ondemand/blob/bee35f9992d7de410f89b365af1be001300cdb03/apps/dashboard/public/noVNC-1.0.0/app.v2.js#L9545-L9548

**Comment by MorganRodgers** [comment] 2020-01-06 18:41
noVNC is aware of this issue and it was fixed in later versions: https://github.com/novnc/noVNC/pull/1074.

**Comment by johrstrom** [comment] 2020-03-09 13:50
I can confirm that this is resolved in no vnc 1.1.0 which is in the process of being merged, so I'm not sure if there's anything for us to do.

**Comment by ericfranz** [comment] 2020-03-20 11:17
After novnc 1.1.0 is in, next step is to consider re-applying c9cd8b266e5be277976e64187ed70d4fe0ecb1e0. A regular revert will not work because we are now generating the app.js from source files.

**Comment by ericfranz** [comment] 2020-05-05 15:48
NoVNC 1.1.0 was added in 1.7 which should prevent this problem. #455 addresses re-adding back the copy/paste fix. Closing this issue.

**Closed by ericfranz** 2020-05-05 15:48 UTC
Labels: bug
