### ISSUE TITLE
Dashboard: Rendering Apps May Cause Internal Server Error

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#102] opened 2019-11-06 16:46 UTC
@johrstrom and I have both experienced errors when interacting with Batch Connect apps. I captured the following:

![Screen Shot 2019-11-06 at 11 39 41 AM](https://user-images.githubusercontent.com/13316545/68318550-fab6eb00-008a-11ea-936a-22ea577d6f79.png)

Note how ActionTemplate is attempting to render a path that is a combination of the system app root and the BatchConnect session id. Despite this error showing the system app path, I only recall this ever happening with development apps; I had just attempted to stop a development version of RStudio.

**Comment by johrstrom** [comment] 2020-11-02 14:45
duplicate of #659

**Closed by johrstrom** 2020-11-02 14:45 UTC
Labels: bug, component/dashboard
