### ISSUE TITLE
Change "version" of components (except for ood-portal-generator) to output the same value as VERSION file for this repo 

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#31] opened 2019-03-01 16:08 UTC
Same logic as https://github.com/OSC/ood-dashboard/blob/baea5558a4e55e8f7ca49599670e6731ad2da94b/config/configuration_singleton.rb#L30-L44

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737622573406) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment] 2023-03-13 18:27
Duplicate of #23

**Closed by johrstrom** 2023-03-13 18:27 UTC
Labels: enhancement
