### ISSUE TITLE
Replace the modal alerts with modeless alerts in the Files app where possible

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#1190] opened 2021-05-29 01:29 UTC
Currently there are many modal alerts that display in the Files app after certain actions fail or the user tries to do certain things they are not allowed to.

[It is preferable to use modeless feedback when possible.](https://www.wiley.com/en-us/About+Face%3A+The+Essentials+of+Interaction+Design%2C+4th+Edition-p-9781118766576)

A dismissable bootstrap alert error could be displayed to the user at the top of the window, for example, that alerts the user without requiring them to dismiss it before proceeding with what the user is doing.

You will need to make sure the alert is visible to the user if they have scrolled down, however. The bootstrap [sticky-top](https://getbootstrap.com/docs/4.0/utilities/position/#sticky-top) class used in the files interface may be useful here, or just ensure its in the stick div.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823219813032) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment] 2024-12-17 19:35
This is a duplicate of #2592 for a variety of reasons. In any, we're getting rid of Sweet alert (which provides these modals) and we're replacing it with https://github.com/OSC/ondemand/blob/master/apps/dashboard/app/javascript/alert.js

**Closed by johrstrom** 2024-12-17 19:35 UTC
Labels: enhancement, component/file_browser
