### ISSUE TITLE
Re-Design Navbar in regards to "Logged in as...", "Help" & Log Out

### ISSUE THREAD

**Issue by gerald-byrket** [OSC/ondemand#2486] opened 2023-01-13 18:37 UTC
We should change the "Logged in as" section to something like this. 

Top Menu = "user's name"

![image](https://user-images.githubusercontent.com/105065813/212375931-d5397f98-052f-4284-9713-a31fab5088ef.png)

From the image above move the following to be under the Top Menu of the "User's Name".  Not necessarily in the order listed.
![image](https://user-images.githubusercontent.com/105065813/212376328-02a42790-6c34-4e4d-82c5-55e8f027fcdb.png)
then this.
* Change HPC Password
* Manage Federated ID
* Log Out

And remove "Log Out" from the Top Level of the Navbar.

_Originally posted by @gerald-byrket in https://github.com/OSC/ondemand/issues/2484#issuecomment-1382138218_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1203792854453508) by [Unito](https://www.unito.io)

**Comment by gerald-byrket** [comment] 2023-01-18 18:31
Your image from the other PR.  This looks great.

<img width="405" alt="Screenshot 2023-01-13 at 20 02 54" src="https://user-images.githubusercontent.com/17336210/212409456-289238ab-c57d-4ac5-a2e0-b136814c03be.png">

**Comment by adaybujeda** [comment] 2023-01-18 20:05
I think the image that I generated is misleading. I was meant to show the menu only, not the actual links inside.

I think the links would be:
**User Menu:**
* Change HPC Password
* Manage Federated ID
* Log Out
* Profile links

**Help:**
* documentation and help links
* restart server
 * support ticket

**Comment by adaybujeda** [comment] 2023-01-19 11:20
Created PR in case you want to push forward with this change.

https://github.com/OSC/ondemand/pull/2499

**Comment by moffatsadeghi** [comment] 2024-08-29 19:35
Duplicate of #435 
Closing as we will work off of issue #435

**Closed by moffatsadeghi** 2024-08-29 19:35 UTC
Labels: area/ux
