### ISSUE TITLE
Feature Request - App Documentation wrapped into Ondemand Interface 

### ISSUE THREAD

**Issue by brandon-biggs** [OSC/ondemand#940] opened 2021-03-11 19:35 UTC
Hi,

Our group was interested in a way to include documentation for specific apps or how-to's inside of the ondemand interface. By the ondemand interface, I just mean with the normal header, footer, navigation bar, etc. I'm not looking for a fully fledged tool like ReadTheDocs or Github pages, just a static page where I could add some documentation for an app or some process written in markdown or html. I could add to the help section at the top of the interactive apps, but some apps may have a lot more than we'd want to put at the top of that page or in a .yml file for the form.

I originally posted this on [discourse](https://discourse.osc.edu/t/documentation-page-on-ondemand/1378) and Jeff suggested adding files and linking to them at /var/www/html. While this is possible and may be the best option, I figured it might be something that could be wrapped into the interface as well.

Example: Someone opens the interactive app for a Jupyter Notebook but doesn’t understand how to use Jupyter Notebooks. Instead of linking them to a general guide on Jupyter Notebooks, I'd like to be able to link them to a sub page that has our own documentation for custom python environments, compute capabilities, etc.

A passenger app might also work for this, and that's something I was going to explore further as well, but I wanted to get this idea out there in case it would be helpful to others.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737650413527) by [Unito](https://www.unito.io)

**Comment by ericfranz** [comment] 2021-03-11 19:57
FWIW there is actually a wiki engine embedded in the Passenger Rails apps that we never disabled: https://github.com/OSC/ood_appkit#wiki-static-page-engine

It is a read only one - so you can drop markdown files in a directory under APP_DIR/wiki/ such as APP_DIR/wiki/Home.md

This was designed so that you could take a wiki from a GitHub repo, clone it to APP_DIR/wiki/ and it would just "work".

Right now if you go to APP_DIR/wiki/ such as APP_DIR/wiki/Home.md you will see an error like

![screen 2021-03-11 at 2 55 27 PM](https://user-images.githubusercontent.com/512333/110846515-d9b36b00-8279-11eb-921e-d066d48e6e9f.png)

This was intended for Rails based passenger apps that were workflow based apps - so an application might be stored in a github repo and the documentation for the application in the wiki, and then deployment would be 2 steps - deploy the app, deploy the wiki.

You would still need to provide a link to the wiki pages from somewhere. And you would be adding a directory below an rpm managed directory, so I don't know the implications of that though @treydock might comment on it.

**Comment by ericfranz** [comment] 2021-03-11 20:09
Hmmm... initial test did not do the rendering I expected to - rather it was trying to send_file for download.

We haven't used this feature in a long time... it might be broken, but it also might be an easy fix. Is this something that interests you @brandon-biggs?

**Comment by treydock** [comment] 2021-03-11 20:31
I am fairly certain a directory like `/var/www/ood/apps/sys/dashboard/wiki` will persist through RPM upgrades but might get deleted during uninstall or saved with `.rpmsave` suffix.

**Comment by ericfranz** [comment] 2021-05-28 12:58
With custom widgets in 2.0, there is an interesting implementation of this feature.

A custom widget could display the home page rendered in markdown for a wiki. This could be a widget that by default is included in the layout and appears if a Home.md is added.

We would want to upgrade this wiki support in OnDemand 2.0 to include:

1. breadcrumbs at the top we use on other pages in the dashboard
2. adding a directory in /etc/ to the load path for these pages, for example /etc/ood/config/apps/dashboard/wiki/ and if Home.md exists in that directory that is used instead of a Home.md in the /var/www/ood/apps/sys/dashboard/wiki/ directory

**Comment by brandon-biggs** [comment] 2021-06-16 21:38
@ericfranz Hi Eric, sorry for not responding sooner. I must have missed the notification of getting tagged. When I read your initial message about the wiki, that sounded great. Like you mentioned though, it also wasn't rendering for me exactly as intended. Something like that would be perfect. Seems simple, easy to keep updated, etc. If something like this would be possible, I think it'd be really helpful. Thanks for exploring this.

**Comment by moffatsadeghi** [comment] 2024-10-17 20:03
This can be done with custom pages since version 3.0.  Please see our documentation on how to do this here: https://osc.github.io/ood-documentation/latest/customizations.html#custom-pages 

Brandon, sorry for the delay.  Your incredible chatbot you recently created seems like an additional great resource for this idea. Closing issue.

**Closed by moffatsadeghi** 2024-10-17 20:03 UTC
Labels: community request, component/dashboard, area/documentation, epic
