### ISSUE TITLE
Launch File Navigator when click on "Select Path" in Code Server Form

### ISSUE THREAD

**Issue by gbyrket** [OSC/ondemand#1996] opened 2022-05-06 15:03 UTC
Launch File Navigator when click on "Select Path" in Code Server Form

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202815755532406/1203340874010024) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment] 2023-04-27 15:19
This is a duplicate of #1571.

**Closed by johrstrom** 2023-04-27 15:19 UTC
Labels: enhancement, component/dashboard, component/batch_connect, epic
