### ISSUE TITLE
Specifying DEX tls_key and tls_cert fails to set tlsKey in /etc/ood/dex/config.yaml

### ISSUE THREAD

**Issue by bviviano** [OSC/ondemand#2162] opened 2022-07-26 17:06 UTC
Host setup

```
[root@host1 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.6 (Ootpa)

[root@host1 ~]# rpm -q ondemand
ondemand-2.0.27-1.el8.x86_64
```

Inside `/etc/ood/config/ood_portal.yml`, if you specify a separate tls_key and tls_cert value for DEX, like the following:
```
dex:
  ssl: true
  tls_key: /etc/pki/tls/private/server.key
  tls_cert: /etc/pki/tls/certs/server.cer
```

Then `tlsKey` isn't added to `/etc/ood/dex/config.yaml`
```
[root@host1 ~]# grep "^[[:space:]]*tls_" /etc/ood/config/ood_portal.yml 
  tls_key: /etc/pki/tls/private/server.key
  tls_cert: /etc/pki/tls/certs/server.cer

[root@host1 ~]# /opt/ood/ood-portal-generator/sbin/update_ood_portal
No change in Apache config.
Backing up previous Dex config to: '/etc/ood/dex/config.yaml.20220726T125735'
mv /etc/ood/dex/config.yaml /etc/ood/dex/config.yaml.20220726T125735
Generating new Dex config at: /etc/ood/dex/config.yaml
mv /tmp/dex_config20220726-91629-nqp1t3 /etc/ood/dex/config.yaml
chown ondemand-dex:ondemand-dex /etc/ood/dex/config.yaml
chmod 600 /etc/ood/dex/config.yaml
Completed successfully!

Restart the ondemand-dex service now.

Suggested command:
    sudo systemctl restart ondemand-dex.service

[root@portal1 ~]# grep tls /etc/ood/dex/config.yaml
  tlsCert: "/etc/pki/tls/certs/server.cer"
[root@host1 ~]# 
```

If I JUST set `tls_key`, but leave `tls_cert` empty, it correctly assigns `tlsKey`, but of course sets nothing for `tlsCert`:
```
[root@host1 ~]# grep "^[[:space:]]*tls_" /etc/ood/config/ood_portal.yml 
  tls_key: /etc/pki/tls/private/server.key

[root@host1 ~]# /opt/ood/ood-portal-generator/sbin/update_ood_portal
No change in Apache config.
Backing up previous Dex config to: '/etc/ood/dex/config.yaml.20220726T125841'
mv /etc/ood/dex/config.yaml /etc/ood/dex/config.yaml.20220726T125841
Generating new Dex config at: /etc/ood/dex/config.yaml
mv /tmp/dex_config20220726-91693-16848zf /etc/ood/dex/config.yaml
chown ondemand-dex:ondemand-dex /etc/ood/dex/config.yaml
chmod 600 /etc/ood/dex/config.yaml
Completed successfully!

Restart the ondemand-dex service now.

Suggested command:
    sudo systemctl restart ondemand-dex.service

[root@host1 ~]# grep tls /etc/ood/dex/config.yaml
  tlsKey: "/etc/pki/tls/private/server.key"
[root@host1 ~]# 
```

**Comment by treydock** [comment] 2022-07-26 17:23
The logic isn't great but then intended behavior was that you use same certs for Apache as you do Dex since they will almost always be served by same host address.  So you define the SSL configs in ood_portal like this:

```yaml
ssl:
  - 'SSLCertificateFile /etc/pki/tls/certs/server.cer'
  - 'SSLCertificateKeyFile /etc/pki/tls/private/server.key'
```

Then when you run the ood-portal-generator commands it will put copies of those files into location Dex user can read and then update configs accordingly. 

https://osc.github.io/ood-documentation/latest/installation/add-ssl.html

**Comment by bviviano** [comment] 2022-07-26 17:30
I understand that, but the Dex Configure Reference clearly states you should be able to override those values with different certificates, if that is a requirement:

https://osc.github.io/ood-documentation/latest/authentication/dex.html#ondemand-dex-configuration-reference
```
tls_cert (String, null)
The path to TLS cert used by Dex. The default is to use the SSL certificate for OnDemand if OnDemand is configured with SSL. Used to define web -> tlsCert in the Dex configuration. If using the OnDemand certificate, a copy is made to /etc/ood/dex. The ondemand-dex user must be able to read this file if configured.
```
```
tls_key (String, null)
The path to TLS key used by Dex. The default is to use the SSL key for OnDemand if OnDemand is configured with SSL. Used to define web -> tlsKey in the Dex configuration. If using the OnDemand key, a copy is made to /etc/ood/dex. The ondemand-dex user must be able to read this file if configured.
```

That fact that using `tls_key` and `tls_cert` results in a broken `/etc/ood/dex/config.yaml` configuration file that prevents the ondemand-dex service from starting is a bug, so I am reporting that bug.

**Comment by treydock** [comment] 2022-07-26 17:40
Should be fixed in https://github.com/OSC/ondemand/pull/2163

**Comment by bviviano** [comment] 2022-07-26 17:40
Thanks.

**Closed** 2022-07-26 19:23 UTC
