### ISSUE TITLE
Files polling caught in 404 loop

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1111] opened 2021-05-07 14:33 UTC
I think I deleted a file, and the action may have occured so quickly that the javascript was never able to find that transfer id correctly.  Now it's in an infinite loop looking for a transfer ID that is gone and should never exist.

![image](https://user-images.githubusercontent.com/4874123/117464908-1f5d7e80-af1f-11eb-849f-d8da74026c4f.png)

Seems to be caught in this function.  If we fail we just keep trying to get updates?  Seems like maybe we'd have to put a limit on how many retires we do and/or deal with 404s specifically.
https://github.com/OSC/ondemand/blob/e37be50c554fc8fddc5be28e3b533e9b625a1606/apps/dashboard/app/views/files/index.html.erb#L780-L801

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737304670447) by [Unito](https://www.unito.io)

**Comment by msquee** [comment] 2021-05-13 20:01
@johrstrom Do you remember if you deleted just 1 file or many? File or directory?

I haven't been able to reproduce this, but a solution I'll go with is to add a request counter and stop after some arbitrary amount of retries like 3 or 5.

In the future we would want to introduce a header `X-OOD-Retires-Allowed` to solve this server side.

**Comment by johrstrom** [comment] 2021-05-14 16:39
No I don't recall, and I also can't replicate. I guess I should have actually looked to see what triggered this. 

But I think it comes from this else block, so you could just comment it to force it to happen.

https://github.com/OSC/ondemand/blob/d60ad74de50bb2ac1fa62d5c5c66a22b1412d51f/apps/dashboard/app/controllers/transfers_controller.rb#L4-L15

I think 3 or 5 consecutive failures is good to kick out (and maybe throw an alert?).

Though, I'm not sure about the header. It's just not guaranteed. Like apache or nginx can fail before the app even sees the request. Or a 50x from the app may not even write it.

**Comment by johrstrom** [comment] 2021-05-26 02:33
I was able to replicate this issue. Apparently the transfers API can return an ID for a transfer that never actually started?  In any case I tried to delete a folder and it just ... didn't happen, then got caught into this loop.

request
![image](https://user-images.githubusercontent.com/4874123/119593976-f48d7a00-bda8-11eb-83af-bae7e7263f71.png)

response
![image](https://user-images.githubusercontent.com/4874123/119593924-dde72300-bda8-11eb-94bd-c6e8c6e36d3b.png)

**Comment by ericfranz** [comment] 2021-05-26 16:35
>I tried to delete a folder and it just ... didn't happen

Seems like a bug if you can attempt to remove a directory and it doesn't actually do so. A clear set of steps to reproduce are required for this I think.

**Comment by ericfranz** [comment] 2021-05-26 16:38
Preferable a set of steps that could be turned into a test added after this automated test for removing a directory that works https://github.com/OSC/ondemand/blob/20a14ff1efccc5755d3565be59c8e0f215905ae9/apps/dashboard/test/system/files_test.rb#L121-L139

**Comment by ericfranz** [comment] 2021-05-26 16:58
Note I added the comment about an automated test to #1172 since it is more relevant there.

**Comment by lukew3** [comment] 2022-07-21 17:59
Closed by #1298

**Closed by lukew3** 2022-07-21 17:59 UTC
Labels: bug, component/file_browser, for review
